--- !ruby/object:Internet_forum
title: title
description: description
accounts:
- !ruby/object:Account
  privilege: Administrator
  pass: |
    pass
  name: |
    admin
  email: |
    asd
  birth_year: |
    asd
  topics: []
  replies: []
- !ruby/object:Account
  privilege: ''
  pass: |
    john
  name: |
    john
  email: |
    john
  birth_year: |
    john
  topics: []
  replies: []
categories:
- !ruby/object:Category
  name: |
    sportas
  description: |
    apie sporta
  forums:
  - !ruby/object:Forum
    title: |
      asd
    description: |
      asd
    topics:
    - &1 !ruby/object:Topic
      title: |
        l
      replies:
      - &2 !ruby/object:Reply
        owner: &3 !ruby/object:Account
          privilege: Administrator
          pass: slapt
          name: vardas
          email: pastas
          birth_year: year
          topics:
          - *1
          replies:
          - *2
        time: 2014-10-25 13:26:20.540072715 +03:00
        text: |
          l
        quotes: []
        last_edit_time: 
        last_edit_owner: 
      owner: *3
      users_who_rated: []
      ratings: []
- !ruby/object:Category
  name: |
    blynai
  description: |
    apie blynus
  forums: []
- !ruby/object:Category
  name: |
    asd
  description: |
    asd
  forums: []
- !ruby/object:Category
  name: |
    niekas
  description: |
    apie nieka
  forums: []
